<?xml version="1.0" encoding="utf-8"?><Database Name="MoeSto" Class="DataAccessManagerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=MoeSto;Integrated Security=True" SettingsObjectName="MoeSto.DAC.Properties.Settings" SettingsPropertyName="MoeStoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Companies" Member="Companies">
    <Type Name="Companies">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Companies_CompanyDetail" Member="CompanyDetails" ThisKey="Id" OtherKey="Id" Type="CompanyDetails" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Images" Member="Images">
    <Type Name="Images">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MainImage" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Images_CompanyDetail" Member="CompanyDetails" ThisKey="Id" OtherKey="MainImageId" Type="CompanyDetails" />
      <Association Name="CompanyDetail_Images" Member="CompanyDetail" ThisKey="CompanyId" OtherKey="Id" Type="CompanyDetails" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CompanyDetails" Member="CompanyDetails">
    <Type Name="CompanyDetails">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Unp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CatalogUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phones" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FoundOnCardone" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CardoneStatus" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CardoneContractNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CardoneContractStatus" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="MainImageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="CompanyDetail_Images" Member="Images" ThisKey="Id" OtherKey="CompanyId" Type="Images" />
      <Association Name="Companies_CompanyDetail" Member="Companies" ThisKey="Id" OtherKey="Id" Type="Companies" IsForeignKey="true" />
      <Association Name="Images_CompanyDetail" Member="Images2" ThisKey="MainImageId" OtherKey="Id" Type="Images" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetCompanyDetailsById" Method="GetCompanyDetailsById" IsComposable="true">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetCompanyDetailsByIdResult1">
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phones" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>